### ISSUE TITLE
Feature : support multiple version of bob2svg

### ISSUE THREAD

**Issue by mbarkhau** [mbarkhau/markdown-svgbob#5]
Re: https://github.com/mbarkhau/asciigrid/issues/5

@PHHENS wrote:

> It would be nice to allow bob2svg version selection on asciigrid editor.
> In some cases, older versions might be more efficient (0.4.1, 0.5.5 ...).

The README.md says:

> This extension will always use the installed version of svgbob if it is available.

So if you do `cargo install svgbob_cli@0.6.6`, I think it should be used.

**Comment by PHHENS** [comment]
Dear Manuel,
I think cargo installs versions from crates.io repository.
But crates.io does not contains every version (eg 0.4.1).
Do you think it could work if replacing directly the binary into 
/usr/local/lib/python3.9/dist-packages/markdown_svgbob/bin/
directory ??
Thanks

**Comment by mbarkhau** [comment]
Yes, that hack would probably work. You'll have to use the naming convention though and remove any existing binaries there.
